//get atm amount balance
GET http://localhost:3000/atm/api/balanceamount


###
//get atm coin balances
GET http://localhost:3000/atm/api/balances


###
//get atm coin balances
POST http://localhost:3000/atm/api/withdraw HTTP/1.1
content-type: application/json

{ 
    "amount":4983 
}