//get atm amount balance
GET http://localhost:3000/atm/api/balanceamount


###
//get atm denomination balances
GET http://localhost:3000/atm/api/balances


###
//withdraw amount from atm
POST http://localhost:3000/atm/api/withdraw HTTP/1.1
content-type: application/json

{ 
    "amount":1000 
}


###
//refill the atm
POST http://localhost:3000/atm/api/refill HTTP/1.1